[project]
name = "executor-dao"
requirements = []

[repl]
costs_version = 2

[contracts.sde-governance-token-with-lockup]
path = "contracts/extensions/membership/tokens/sde-governance-token-with-lockup.clar"
depends_on = ["executor-dao", "governance-token-trait", "sip010-ft-trait"]

[contracts.sde-proposal-voting-with-lockup]
path = "contracts/extensions/voting/sde-proposal-voting-with-lockup.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "sde-governance-token-with-lockup"]

[contracts.sde-proposal-submission-with-lockup]
path = "contracts/extensions/proposal-submissions/sde-proposal-submission-with-lockup.clar"
depends_on = ["executor-dao", "extension-trait", "sde-proposal-voting-with-lockup"]

[contracts.sde-emergency-proposals]
path = "contracts/extensions/executive-team/sde-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "sde-proposal-voting-with-lockup"]

[contracts.sde-emergency-execute]
path = "contracts/extensions/executive-team/sde-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "sde-proposal-voting-with-lockup"]

[contracts.sde-dev-fund]
path = "contracts/extensions/misc/sde-dev-fund.clar"
depends_on = ["executor-dao", "extension-trait", "sde-governance-token-with-lockup"]

[contracts.sde-membership]
path = "contracts/extensions/membership/sde-membership.clar"
depends_on = ["executor-dao", "member-trait", "extension-trait"]

[contracts.sde-proposal-voting-with-members]
path = "contracts/extensions/voting/sde-proposal-voting-with-members.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "member-trait"]

[contracts.sde-proposal-submission-with-members]
path = "contracts/extensions/proposal-submissions/sde-proposal-submission-with-members.clar"
depends_on = ["executor-dao", "extension-trait", "sde-proposal-voting-with-members"]

[contracts.sde-vault]
path = "contracts/extensions/vaults/sde-vault.clar"
depends_on = ["executor-dao", "extension-trait", "sip009-nft-trait", "sip010-ft-trait"]

[contracts.sde-mia-stacking]
path = "contracts/extensions/misc/sde-mia-stacking.clar"
depends_on = ["executor-dao", "extension-trait"]

[contracts.sde-proposal-voting-with-nft]
path = "contracts/extensions/voting/sde-proposal-voting-with-nft.clar"
depends_on = ["executor-dao", "extension-trait", "nft-membership"]

[contracts.sde-proposal-submission-with-nft]
path = "contracts/extensions/proposal-submissions/sde-proposal-submission-with-nft.clar"
depends_on = ["executor-dao", "extension-trait", "nft-membership", "sde-proposal-voting-with-nft"]

[contracts.sde-multisig]
path = "contracts/extensions/multisignature/sde-multisig.clar"
depends_on = ["executor-dao", "extension-trait", "proposal-trait"]

[contracts.sdp000-bootstrap]
path = "contracts/proposals/sdp000-bootstrap.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "sde-governance-token-with-lockup", "sde-proposal-voting-with-lockup", "sde-proposal-submission-with-lockup", "sde-emergency-proposals", "sde-emergency-execute", "sde-membership", "sde-proposal-voting-with-members", "sde-proposal-submission-with-members", "sde-vault"]

[contracts.sdp001-dev-fund]
path = "contracts/proposals/sdp001-dev-fund.clar"
depends_on = ["sde-governance-token-with-lockup", "executor-dao"]

[contracts.sdp002-kill-emergency-execute]
path = "contracts/proposals/sdp002-kill-emergency-execute.clar"
depends_on = ["sde-emergency-execute", "executor-dao"]

[contracts.sdp003-whitelist-escrow-nft]
path = "contracts/proposals/sdp003-whitelist-escrow-nft.clar"
depends_on = ["proposal-trait", "nft-escrow"]

[contracts.sdp004-send-funds]
path = "contracts/proposals/sdp004-send-funds.clar"
depends_on = ["proposal-trait"]

[contracts.sdp005-disable-emergency-proposal]
path = "contracts/proposals/sdp005-disable-emergency-proposal.clar"
depends_on = ["proposal-trait"]

[contracts.sdp006-add-member]
path = "contracts/proposals/sdp006-add-member.clar"
depends_on = ["proposal-trait"]

[contracts.sdp007-add-signer]
path = "contracts/proposals/sdp007-add-signer.clar"
depends_on = ["proposal-trait"]

[contracts.executor-dao]
path = "contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.member-trait]
path = "contracts/traits/member-trait.clar"
depends_on = []

[contracts.nft-escrow]
path = "contracts/external/nft-escrow.clar"
depends_on = ["ownable-trait"]

[contracts.nft-membership]
path = "contracts/external/nft-membership.clar"
depends_on = ["sip009-nft-trait"]

[contracts.ft-membership]
path = "contracts/external/ft-membership.clar"
depends_on = ["sip010-ft-trait"]

[contracts.citycoin-auth]
path = "contracts/external/citycoins/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-core-trait]
path = "contracts/external/citycoins/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-core-v1]
path = "contracts/external/citycoins/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-token]
path = "contracts/external/citycoins/citycoin-token.clar"
depends_on = ["sip010-ft-trait", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-token-trait]
path = "contracts/external/citycoins/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-vrf]
path = "contracts/external/citycoins/citycoin-vrf.clar"
depends_on = []

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []

[contracts.sdp006-test-bootstrap]
path = "contracts/tests/proposals/sdp006-test-bootstrap.clar"
depends_on = ["proposal-trait", "executor-dao", "sde-vault", "sde-membership", "sde-proposal-voting-with-members", "sde-proposal-submission-with-members"]

[contracts.sde006-test-membership]
path = "contracts/tests/extensions/sde006-test-membership.clar"
depends_on = []

[contracts.sdp008-test-bootstrap]
path = "contracts/tests/proposals/sdp008-test-bootstrap.clar"
depends_on = ["proposal-trait", "executor-dao", "sde-vault", "sde-membership", "sde-proposal-voting-with-members", "sde-proposal-submission-with-members"]

[contracts.sdp008-test-proposal-submission]
path = "contracts/tests/proposals/sdp008-test-proposal-submission.clar"
depends_on = ["proposal-trait", "executor-dao", "sde006-test-membership", "sde-membership"]