export const CONTRACTS = {
  executorDao: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.executor-dao",
};

export const EXTENSIONS = {
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-vault",
  MULTISIG: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-multisig",
  DELEGATE_PROPOSAL_SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-proposal-submission-with-delegation",
};

export const GOVERNANCE = {
  DELEGATE_TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-governance-token-with-delegation",
  NFT_TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.nft-membership",
}

export const BOOTSTRAPS = {
  MULTISIG_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-multisignature-dao",
  DELEGATE_VOTING_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-delegate-voting-dao",
  NFT_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-nft-dao",
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-vault",
};

export const PROPOSALS = {
  SDP_TRANSFER_FUNGIBLE_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-transfer-ft",
  SDP_UNAUTHORIZED_TRANSFER_STX: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-unauthorized-transfer-stx",
  SDP_ADD_SIGNER: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-add-signer",
};

export const FUNGIBLE_TOKENS = {
  CITY_COIN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.citycoin-token",
  DELEGATE_TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-governance-token-with-delegation",
  FT_MEMBERSHIP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ft-membership",
};

export const NON_FUNGIBLE_TOKENS = {
  NFT_MEMBERSHIP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.nft-membership",
};

// ERROR CODES

export enum EXECUTOR_DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};

export enum VAULT_CODES {
  ERR_UNAUTHORIZED = 3200,
  ERR_ASSET_NOT_WHITELISTED = 3201,
  ERR_FAILED_TO_TRANSFER_STX = 3202,
  ERR_FAILED_TO_TRANSFER_FT = 3203,
  ERR_FAILED_TO_TRANSFER_NFT = 3204,
};

export enum MULTISIG_CODES {
  ERR_UNAUTHORIZED = 3600,
  ERR_NOT_SIGNER = 3601,
  ERR_INVALID = 3602,
  ERR_ALREADY_EXECUTED = 3603,
  ERR_PROPOSAL_NOT_FOUND = 3604,
  ERR_PROPOSAL_ALREADY_EXISTS = 3605,
  ERR_PROPOSAL_ALREADY_EXECUTED = 3606,
};

export enum NFT_VOTING_CODES {
  ERR_UNAUTHORIZED = 3400,
  ERR_NOT_NFT_OWNER = 3401,
  ERR_PROPOSAL_ALREADY_EXECUTED = 3402,
  ERR_PROPOSAL_ALREADY_EXISTS = 3403,
  ERR_UNKNOWN_PROPOSAL = 3404,
  ERR_PROPOSAL_ALREADY_STARTED = 3405,
  ERR_PROPOSAL_ALREADY_CONCLUDED = 3406,
  ERR_PROPOSAL_INACTIVE = 3407,
  ERR_PROPOSAL_NOT_CONCLUDED = 3408,
  ERR_NO_VOTES_TO_RETURN = 3409,
  ERR_ALREADY_VOTED = 3410,
  ERR_END_BLOCK_HEIGHT_NOT_REACHED = 3411,
  ERR_DISABLED = 3412,
};

export enum NFT_SUBMISSION_CODES {
  ERR_UNAUTHORIZED = 3500,
  ERR_NOT_NFT_OWNER = 3501,
  ERR_UNKNOWN_PARAMETER = 3502,
  ERR_PROPOSAL_MINIMUM_START_DELAY = 3503,
  ERR_PROPOSAL_MAXIMUM_START_DELAY = 3504,
};

export enum DELEGATE_GOVERNANCE_CODES {
  ERR_UNAUTHORIZED = 2400,
  ERR_NOT_TOKEN_OWNER = 2401,
  ERR_NOT_ENOUGH_TOKENS = 2403,
  ERR_INVALID_WEIGHT = 2404,
  ERR_MUST_REVOKE_CURRENT_DELEGATION = 2405,
  ERR_NO_DELEGATION_TO_REVOKE = 2406,
};

export enum DELEGATE_VOTING_CODES {
  ERR_UNAUTHORIZED = 2500,
  ERR_NOT_GOVERNANCE_TOKEN = 2501,
  ERR_PROPOSAL_ALREADY_EXECUTED = 2502,
  ERR_PROPOSAL_ALREADY_EXISTS = 2503,
  ERR_UNKNOWN_PROPOSAL = 2504,
  ERR_PROPOSAL_ALREADY_ACTIVE = 2505,
  ERR_PROPOSAL_ALREADY_CONCLUDED = 2506,
  ERR_PROPOSAL_INACTIVE = 2507,
  ERR_PROPOSAL_NOT_CONCLUDED = 2508,
  ERR_NO_VOTES_TO_RETURN = 2509,
  ERR_QUORUM_NOT_MET = 2510,
  ERR_END_BLOCK_HEIGHT_NOT_REACHED = 2511,
  ERR_DISABLED = 2512,
  ERR_INSUFFICIENT_WEIGHT = 2513,
  ERR_ALREADY_VOTED = 2514,
  ERR_UNKNOWN_PARAMETER = 2515,
};

export enum DELEGATE_SUBMISSION_CODES {
  ERR_UNAUTHORIZED = 2600,
  ERR_NOT_GOVERNANCE_TOKEN = 2601,
  ERR_INSUFFICIENT_WEIGHT = 2602,
  ERR_UNKNOWN_PARAMETER = 2603,
  ERR_PROPOSAL_MINIMUM_START_DELAY = 2604,
  ERR_PROPOSAL_MAXIMUM_START_DELAY = 2605,
};