export const CONTRACTS = {
  executorDao: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.executor-dao",
};

export const EXTENSIONS = {
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-vault",
  DELEGATE_PROPOSAL_SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-proposal-submission-with-delegation",
};

export const GOVERNANCE = {
  DELEGATE_TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sde-governance-token-with-delegation",
}

export const BOOTSTRAPS = {
  DEFAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp000-bootstrap",
  DELEGATE_VOTING_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-delegate-voting-dao",
};

export const PROPOSALS = {
  SDP_TRANSFER_FUNGIBLE_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-transfer-fungible-tokens",
};